# Form implementation generated from reading ui file 'D:\Dev\SpeechClipboard\speech.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtKey = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtKey.setGeometry(QtCore.QRect(130, 310, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.txtKey.setFont(font)
        self.txtKey.setText("")
        self.txtKey.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.txtKey.setObjectName("txtKey")
        self.lblKey = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblKey.setGeometry(QtCore.QRect(30, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblKey.setFont(font)
        self.lblKey.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblKey.setObjectName("lblKey")
        self.lblRegion = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRegion.setGeometry(QtCore.QRect(200, 350, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblRegion.setFont(font)
        self.lblRegion.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblRegion.setObjectName("lblRegion")
        self.cmbRegion = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbRegion.setGeometry(QtCore.QRect(300, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbRegion.setFont(font)
        self.cmbRegion.setObjectName("cmbRegion")
        self.txtMain = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtMain.setGeometry(QtCore.QRect(10, 10, 621, 291))
        self.txtMain.setObjectName("txtMain")
        self.cmbVoice = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbVoice.setGeometry(QtCore.QRect(300, 400, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbVoice.setFont(font)
        self.cmbVoice.setObjectName("cmbVoice")
        self.lblVoice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblVoice.setGeometry(QtCore.QRect(200, 390, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblVoice.setFont(font)
        self.lblVoice.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblVoice.setObjectName("lblVoice")
        self.btnRec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRec.setGeometry(QtCore.QRect(510, 310, 121, 51))
        self.btnRec.setObjectName("btnRec")
        self.btnReadAloud = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReadAloud.setGeometry(QtCore.QRect(510, 370, 121, 61))
        self.btnReadAloud.setObjectName("btnReadAloud")
        self.btnSaveSettings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSaveSettings.setEnabled(False)
        self.btnSaveSettings.setGeometry(QtCore.QRect(440, 310, 61, 121))
        self.btnSaveSettings.setObjectName("btnSaveSettings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtKey.setPlaceholderText(_translate("MainWindow", "171b57f4b6210ee59816347d55e18b81"))
        self.lblKey.setText(_translate("MainWindow", "Key"))
        self.lblRegion.setText(_translate("MainWindow", "Region"))
        self.lblVoice.setText(_translate("MainWindow", "Voice"))
        self.btnRec.setText(_translate("MainWindow", "REC FILE"))
        self.btnReadAloud.setText(_translate("MainWindow", "READ ALOUD"))
        self.btnSaveSettings.setText(_translate("MainWindow", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
